; KryonOS - plataforma de build
;
; envs:
;   esp32doit-devkit-v1     - placa classica: ESP32 DevKit + ILI9341 2.8" SPI 240x320 + XPT2046
;   smartdisplay_4848S040   - Guition ESP32-S3-4848S040 (SmartDisplay ESP32-S3 4.0"):
;                             ESP32-S3-N16R8, display 4" 480x480 ST7701 RGB, touch GT911

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
board_build.filesystem = littlefs
board_build.partitions = min_spiffs.csv

monitor_speed = 115200

lib_deps =
    bodmer/TFT_eSPI@^2.5.43
    bblanchon/ArduinoJson @ 7.1.0
    mathieucarbou/ESPAsyncWebServer @ 3.1.5

build_flags =
    -D KRYONOS_VERSION=\"1.0.0\"
    -D KRYONOS_API_LEVEL=2
    -D USER_SETUP_LOADED=1
    -D ILI9341_DRIVER=1
    -D TFT_MISO=19
    -D TFT_MOSI=23
    -D TFT_SCLK=18
    -D TFT_CS=17
    -D TFT_DC=16
    -D TFT_RST=5
    -D TOUCH_CS=21
    -D LOAD_GLCD=1
    -D LOAD_FONT2=1
    -D LOAD_FONT4=1
    -D SMOOTH_FONT=1
    -D SPI_FREQUENCY=27000000
    -D SPI_READ_FREQUENCY=20000000
    -D SPI_TOUCH_FREQUENCY=2500000

[env:smartdisplay_4848S040]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
board_build.filesystem = littlefs
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv

monitor_speed = 115200
upload_speed = 921600

lib_deps =
    lovyan03/LovyanGFX@^1.2.0
    bblanchon/ArduinoJson @ 7.1.0
    mathieucarbou/ESPAsyncWebServer @ 3.1.5

build_flags =
    -D KRYONOS_VERSION=\"1.0.0\"
    -D KRYONOS_API_LEVEL=2
    -D KRYONOS_BOARD_SMARTDISPLAY_4IN=1
    -D BOARD_HAS_PSRAM
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=0
